### PR TITLE
Jonathan Cannon nodeLOM

### PR DESCRIPTION
**Pull request by iamjoncannon**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors -- `npm run lint`, from the root of the n4m-examples repository, not within your example folder
* [x] your example is well documented—make sure there is a `README.md` in your example folder
* [x] your example has been added to the root `README.md` file

Thank you!

### CODE REVIEW

**Comment by iamjoncannon** [comment]
Have fun!

**Comment by starakaj** [comment]
Hey, this is super cool and I'm really excited to give people the chance to experiment with it. Controlling a live set from Node definitely opens up a lot of possibilities for composition and live performance.

Before we can merge this pull request, there a few things that need to be fixed. When I run "npm run lint" in the directory root, the tool comes back with linting errors in `LOM.js`, `LOMjsObj.js` and `LOMnodeObj.js`. Many of the errors in `LOMjsObj.js` are due to the fact that Max defines certain globals for js objects (outlets and LiveAPI for example) and it's okay to ignore these. You can use eslint to turn off specific rules at the top of the file (see https://eslint.org/docs/user-guide/configuring.html#configuring-rules and https://stackoverflow.com/questions/34764287/turning-off-eslint-rule-for-a-specific-file). The other files need their linting errors fixed.

The README file (which should be named README.md, using caps) needs to have its installation steps updated. It still references https://github.com/iamjoncannon/nodeLOM and still asks the user to install `socket.io` specifically, but `npm install` uses `package.json` to install this dependency anyway.

In my opinion, the Live device itself could use a little bit of love. It would be nice, for example, to have some feedback that the server started correctly, and that it's listening on 8080. It might also be useful to have a log or an indicator when new messages come in, to give the user feedback that everything is running smooth. Just suggestions, but these could help make the device more approachable for a new user.

Finally, this example needs a demo file that shows how to use `LOM.js`. There is some info in the README, but a working example would really help a new user to understand how to get things running. The code that is in the README needs work too. For example:

```
const LOM = require("./maxLOM/LOM.js")
```

assumes that the file is placed outside of the folder containing `LOM.js`, and that the folder containing `LOM.js` is named `maxLOM`. But in this example the folder is named `nodeLOM`. Things like this make it hard for a new user to get started.

Getting these fixes in places would make this example much more solid, I think. As I say, it's a very cool example that I know people are interested in, so I'm looking forward to getting this example merged. Thanks!

**Comment by catarak** [comment]
@iamjoncannon we've decided to split up this repository into Cycling '74 examples and community examples. because of this, I've added a link to your example in the new [community repository](https://github.com/Cycling74/n4m-community). you can make updates to your own repository and not have to adhere to the Cycling '74 linting rules. i think a lot of @starakaj's feedback, however, is still valid and could add some polish to your example! let me know if you have any questions.

**Comment by pixlpa** [comment]
Hi @iamjoncannon , I'd love to include a brief profile of this work in the next Cycling '74 newsletter. Any interest in a brief email interview? Contact me at andrewb@cycling74.com at your earliest convenience. Best, Andrew

**Comment by iamjoncannon** [comment]
Hi Andrew,

More than happy to answer questions!

I will be finishing up my edits on the project this weekend, I wanted to
put some time into a functional example.

best,
jc

**Pull request closed without merging**
